---
abstract: 'PSGI handler for HTTP::Server::Simple'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Server-Simple-PSGI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::Server::Simple: 0.41
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/HTTP-Server-Simple-PSGI.git
version: 0.10
